name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web

      - name: Zip build files
        run: |
          cd build
          zip -r web.zip web

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload zip file to S3
        run: aws s3 cp build/web.zip s3://toonsutra-web-app-winjit/web.zip --acl public-read
